### ISSUE TITLE
How to display one string to the console(terminal) by asm program?

### ISSUE THREAD

**Issue by clx7913** [riscv/riscv-asm-manual#11]
I've seen this example:
https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md#constants

Whether the function of "puts" here is displaying string "Hello World\n"?I tried to build the program,but there seems no displaying.This example should work with UART?

**Comment by jim-wilson** [comment]
It is just an assembly example.  It doesn't necessarily work on hardware or simulators.  Even if it does, whether it works depends on what uart you have, and your hardware/simulator doesn't necessarily have the same uart as the author.

If you want code that works on hardware/simulator, you shouldn't be looking in an assembly language manual.  You should be looking at hardware/simulator projects.  Such as freedom-e-sdk or freedom-u-sdk for instance.

**Comment by clx7913** [comment]
I just want to run my built assembly program on rocket-chip implemented in Zedboard by `./fesvr program`.

If the assembly program doesn't have output on the terminal/console,it's not convenient to verify on the rocket-chip hardware.I haven't other good verification ideas.Could you give me  some advice?

**Comment by clx7913** [comment]
OK，I'll check it.

Sorry to trouble you and thanks again!
