### ISSUE TITLE
what is .option {rvc,norvc,pic,nopic,push,pop} RISC-V options?

### ISSUE THREAD

**Issue by decentsheep** [riscv/riscv-asm-manual#19]
I have a question about a line in riscv-asm-manual, what does  .option | {rvc,norvc,pic,nopic,push,pop} | RISC-V options mean? and any documents about rvc, norvc, pic, nopic, push, pop?

**Comment by jim-wilson** [comment]
There is some documentation in the GNU as manual
https://sourceware.org/binutils/docs-2.31/as/RISC_002dV_002dDirectives.html#RISC_002dV_002dDirectives

It probably should be mentioned in this manual also.

**Comment by decentsheep** [comment]
@jim-wilson thanks a lot!
