### ISSUE TITLE
jalr issue

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-asm-manual#27]
Hi
   When i compile these, i got error:

```
.section .text
.global _start
_start:
    lui     a1, %hi(msg)
    addi    a1,a1,%lo(msg)
    jalr    ra, puts
2:  j 2b

.section .rodata
msg:
    .string "Hello World\n"
```
```
/root/workspace/riscv>riscv-none-embed-as a.s
a.s: Assembler messages:
a.s:6: Error: illegal operands `jalr ra,puts'
```

```
/root/workspace/riscv>riscv-none-embed-as -v
GNU assembler version 2.32 (riscv-none-embed) using BFD version (xPack GNU RISC-V Embedded GCC, 64-bit) 2.32
```

thanks
Peter

**Comment by jim-wilson** [comment]
Perhaps you meant to use jal?  jal takes a 20-bit offset.  jalr takes a reg plus 12-bit offset.  We don't allow symbols with jalr as it isn't useful, this would be x0 as the base register plus a 12-bit offset which can only work if the target is in the low 4KB of memory which is rather unlikely.  jal with a symbol is allowed and gives a 1MB range which is enough to be useful.

If you really want jalr, you can use
    jalr    ra, %lo(puts)(x0)

The standard way to do a call is to use the call macro
   call puts
This expands to
   c:	00000097          	auipc	ra,0x0
			c: R_RISCV_CALL	puts
			c: R_RISCV_RELAX	*ABS*
  10:	000080e7          	jalr	ra # c <main+0xc>
where the R_RISCV_CALL reloc puts the high part of the address offset in the auipc and the low part in the jalr, and the linker will relax this to a jal if in range.  We unfortunately don't have assembler syntax to generate this directly, so you have to use the call macro.  There is also a tail macro for tail calls.

**Comment by jim-wilson** [comment]
But note that
jalr ra, %lo(puts)(x0)
will silently fail if puts is not in the low 4KB of memory.

**Comment by quantrpeter** [comment]
thanks @jim-wilson
