### ISSUE TITLE
Question on the relative addressing example

### ISSUE THREAD

**Issue by Engineev** [riscv/riscv-asm-manual#30]
Hi. I have problems on comprehending the following example on relative addressing.
```
.section .text
.globl _start
_start:
1:	    auipc a0,     %pcrel_hi(msg) # load msg(hi)
	    addi  a0, a0, %pcrel_lo(1b)  # load msg(lo)
	    jal ra, puts
2:	    j 2b

.section .rodata
msg:
	    .string "Hello World\n"
```

As I understand it, %pcrel_hi(msg) computes the `(msg - pc)[31:20]` (the higher 20 bits of the offset). Why the next line is `addi a0, a0, %pcrel_lo(1b)`, instead of something like `%pcrel_lo(msg)`?

Also, if my understanding was correct, then there would be another problem. The values of `pc` are different when `auipc` and `addi` get executed. So it seems to be incorrect to simply use `%pcrel_lo(msg)` in `addi`. Am I missing something here?

**Comment by johnwinans** [comment]
I think I can field this one...
%pcrel_lo() is designed to be paired with %pcrel_hi().  The 1b is used to refer to the label 1 (where the corresponding %pcrel_hi is).  When so paired, the address for the pcrel_lo is calculated based on the address that the 1: refers to (not the current pc value) and the address specified in the pcrel_hi that the pair of instructions ultimately refer to.    
There is also the matter of the addi performing a signed addition... which can confuse matters a bit. The recent drafts of the ISA discusses the fact that the linker will add an extra 1 to the hi part of the address compensate for it when needed.
Therefore, making the %pcrel_lo refer to the 1: (as opposed to the msg:) label is how these two items are related.

**Comment by lenary** [comment]
You've actually put together the two important points:
- The `pc` does indeed have different values for the `auipc` and `addi`. There is also no requirement these two are adjacent instructions, so the `pc` can change by more than 4 (or more than 2 if you're using compressed instructions).
- The `%pcrel_lo(1b)` is correct, `1b` means "local label 1, it's before this location".

So, if you combine these:
- the label in `%pcrel_lo` points to an instruction with a `%pcrel_hi` relocation on it, in this case the `auipc a0, %pcrel_hi(msg)`
- When computing the 12-bit immediate to jump to, they use the difference between the instruction with the `%pcrel_hi` and the symbol in the relocation.

This means that the 12-bit immediate written into the `addi` is not pc-relative to the `addi`, it is pc-relative to the `auipc` (and it has to account for the fact it will be added).

I hope this helps clarify what is going on.

**Comment by Engineev** [comment]
Thank you for your explanations ! I understand them now.

**Comment by pdfrod** [comment]
Could we add this really vital explanation to the manual? I was really confused trying to figure out what `%pcrel_lo(1b)` does; I must have spent half an hour scouring the manual for any hints.
