### ISSUE TITLE
unable to assemble "jal x0,0x1f

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-asm-manual#32]
hi
   i am using gas:

jal x0,0x00 -> give me 6f 00 00 00
jal x0,0x1234 -> give me 6f 10 40 23
jal x0,0x1f give me this error:

temp.o: in function `_start':
(.text+0x0): relocation truncated to fit: R_RISCV_JAL against `*UND*'

why?

thanks
Peter

**Comment by johnwinans** [comment]
You can not jump or branch to an odd address.

**Comment by quantrpeter** [comment]
thanks
