### ISSUE TITLE
c.addi	x2,0b111111 operands

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-asm-manual#35]
Hi
   Why c.addi	x2,0b111111 gives us "a.s:17: Error: illegal operands `c.addi x2,0b110000'". The IMM of CI Type should have 6 bits.
Thanks
Peter

**Comment by lenary** [comment]
`c.addi`'s immediate is a non-zero sign-extended 6-bit immediate. The issue probably comes because `0b111111` is being parsed into some wider bitwidth with the upper bits all zeroes, (something like `0b00111111`) which is not representable as a two's complement signed 6-bit number.

**Comment by quantrpeter** [comment]
if i "c.addi	x2,-1", it encoded 117d, which nzimm field are 0b111111. So i think it is gas bug

**Comment by aswaterman** [comment]
As Sam said, 0b111111 is probably being interpreted as 63, not -1. But the largest positive value allowed is 31. Seems like not a bug.

**Comment by jim-wilson** [comment]
I get an illegal operands error for "c.addi x2,0b111111" which looks correct to me, because 0b111111 is 63 which doesn't fit in a signed 6-bit immediate.  The valid range is -32 to 31.  You can't easily use binary, octal, or hex to specify negative numbers.

**Comment by quantrpeter** [comment]
@jim-wilson thanks for your great answer
