### ISSUE TITLE
Minor typo in example

### ISSUE THREAD

**Issue by ComponentFactory** [riscv/riscv-asm-manual#4]
Inside the relative addressing example, you use '1b' inside the '%pcrel_lo' when I think it should be 'msg'.

    addi  a1, a1, %pcrel_lo(1b)  # load msg(lo)

**Comment by aswaterman** [comment]
It's correct as-is.  The low part of a PC-relative relocation is relative to the address of the instruction that contains the high part.

**Comment by ComponentFactory** [comment]
Fair enough, my bad.
