### ISSUE TITLE
c.addi should be nzimm (non zero imm)

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-asm-manual#42]
Hi
   c.addi should be nzimm (non zero imm), but when i use objdump to diassemble, i saw -16.

b:     file format elf32-littleriscv

Disassembly of section .text:

00010074 <exit>:
   10074:       1141                    addi    sp,sp,-16

Why?

Thanks
Peter

**Comment by lenary** [comment]
From the spec:

> `C.ADDI` adds the non-zero sign-extended 6-bit immediate to the value in register *rd* then writes the result to *rd*.

The only requirement is that the immediate is non-zero, not that it is positive. 

If the immediate field is all zeroes, then this encodes `C.NOP` or hint instructions (depending on *rd*).

**Comment by quantrpeter** [comment]
my fault, i thought nzimm mean unsign, thanks Lenary. This group is really super helpful. Thank you to all heros here.
