### ISSUE TITLE
sp -4

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-asm-manual#47]
Hi
   when my risc-v mcu start, the SP is 0. If run these two instructions:

 8000000:       7179                    addi    sp,sp,-48
 8000002:       d622                    sw      s0,44(sp)

The first line will change the sp to -48, and then store s0 to -48+44 = -4 , but -4 is fffffffc, which is not an exist memory zone of the mcu, i can't explain this. Please help. Attached is the MCU i am using.

[GD32VF103_User_Manual_EN_V1.0.pdf](https://github.com/riscv/riscv-asm-manual/files/5079014/GD32VF103_User_Manual_EN_V1.0.pdf)

In the elf i see the stack section pointing to ram, but in the code i don't see it stuck the memory address to sp

```
C:\workspace\riscv-simulator\src\test\resources\hk\quantr\riscv_simulator\example_code>riscv-none-embed-readelf -S a.elf
There are 8 section headers, starting at offset 0x215c:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        08000000 001000 0000dc 00  AX  0   0  2
  [ 2] .data             PROGBITS        20000000 002000 000000 00  WA  0   0  1
  [ 3] .bss              NOBITS          20000000 002000 000000 00  WA  0   0  1
  [ 4] .stack            NOBITS          20007c00 002c00 000400 00  WA  0   0  1
  [ 5] .symtab           SYMTAB          00000000 002000 0000e0 10      6   7  4
  [ 6] .strtab           STRTAB          00000000 0020e0 000047 00      0   0  1
  [ 7] .shstrtab         STRTAB          00000000 002127 000033 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)
```

Thanks
Peter

**Comment by lenary** [comment]
Commonly you need to set `sp` in the assembly code that runs before your C code runs. This is called the CRT, and ensures the right environment is presented to C programs. 

This is code is conventionally provided by `crt0.o` and `crtbegin.o` (and some exit-related functionality is provided by `crtend.o`), in newlib's libc (used by not providing `-nostartfiles`) however these are likely wrong for your platform (unless you're using a toolchain specific to your MCU) and instead you will have to hand-write some assembly and a linker script to provide the same functionality.

**Comment by quantrpeter** [comment]
yes, you are right. I didn't init the stack but the cpu just keep running to next instruction. May be this is the characteristics of RISC-V
