### ISSUE TITLE
Will the "tail" pseudo instruction always get transformed to the "jalr" instruction?

### ISSUE THREAD

**Issue by SaiVK** [riscv/riscv-asm-manual#52]
Hello Everyone
   I compiled a C program with _-O2_ flag enabled. On inspecting the assembly file generated by the compiler (_-S_ flag) I noticed a couple of **_tail_** pseudo instruction. But in the object dump file generated, I noticed that the **_tail_**  pseudo instruction gets converted to _**j**_ instruction.
My doubt is, in the explanation given in the manual, it is specified that **_tail_** pseudo instruction gets transformed to **_jalr_**. Is this not followed always?

Thank you so much
Sai

**Comment by aswaterman** [comment]
auipc/jalr is the worst case, with relaxations to j and c.j.

**Comment by SaiVK** [comment]
Hello @aswaterman 
Oh ok, so only when a far-away subroutine is being invoked, the **_tail_** pseudo instruction transforms to an **_auipc + jalr_** instruction. Else, it can transform to **_j_** or **_c.j_** instruction. 
Did I understand it properly?

Thank you so much
Sai

**Comment by aswaterman** [comment]
Yes. Note the linker performs that transformation, so the object code will always show auipc/jalr.

**Comment by SaiVK** [comment]
@aswaterman 
Got it. 
Is it possible to modify the linker such that all **_tail_** pseudo instructions transform only to **_jalr_** instruction and not to **_j_** or _**c.j**_ instruction?

Thank you so much
Sai

**Comment by aswaterman** [comment]
I think you can pass the `--no-relax` flag to the linker.

**Comment by SaiVK** [comment]
@aswaterman 
Oh ok. I will try using that flag. 
Are there any downsides in using that?

Thank you so much
Sai

**Comment by aswaterman** [comment]
Yes - increased code size and lower performance

**Comment by SaiVK** [comment]
Oh ok. Got it.

Thank you so much @aswaterman for taking your time and explaining it to me.
Sai

**Comment by aswaterman** [comment]
You're welcome!
