### ISSUE TITLE
Cover more pseudoinstructions, as it was done in riscv-spec-v2.2

### ISSUE THREAD

**Issue by gevorgyana** [riscv/riscv-asm-manual#54]
This issue https://github.com/riscv/riscv-isa-manual/issues/540 suggested to supersede the section on pseudoinstructions inside RISC-V ISA manual with riscv-asm-manual. We can cover more pseudoinstructions than we do now in this repository - I can't see any mention of `fence`, no mention of "`branch`" pseudoinstructions. Shouldn't we just add the table from the ISA manual 2.2 to the markdown?

**Comment by jim-wilson** [comment]
This is waiting for a volunteer to do the work.  Would you like to submit a patch?

**Comment by gevorgyana** [comment]
Sure @jim-wilson

**Comment by aswaterman** [comment]
Thanks!
