### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by montedalrymple** [riscv/riscv-asm-manual#62]
In the section "A listing of standard RISC-V pseudoinstructions" the descriptions for call and tail specify x6. Should be x1?

**Comment by aswaterman** [comment]
No, this is intentional. We don’t want to push anything to a return-address stack in the case of a tail call, so we want to use a register other than x1 or x5.  x6 is a convenient choice because in the standard ABIs it’s a temporary register.

**Comment by montedalrymple** [comment]
Okay, then table 25.3 in the ISA manual needs to be changed. It says CALL uses x1.

**Comment by montedalrymple** [comment]
Never mind. Just realized that chapter in the ISA manual is going away.

**Comment by aswaterman** [comment]
I did check the assembly manual, and it looks correct. CALL uses x1 and TAIL uses x6.
