### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-asm-manual#65]
The project is missing a LICENSE file. Per RISC-V guidelines, documentation should be licensed CC-BY-4.0.

I propose adding a plain text [LICENSE](https://github.com/riscv/riscv-isa-manual/blob/master/LICENSE) file like the one in the ISA manual project. This enables GitHub to automatically find it and recognize it.

I'm happy to add this into the project directly and will do so in the coming days. If anyone has concerns, please raise them.

Thanks,
-Jeff

**Comment by aswaterman** [comment]
SGTM.

**Comment by jjscheel** [comment]
Thanks, @aswaterman! Done.

Committed directly to master.  Closing.
