### ISSUE TITLE
How to understand the syntax of “0(a0)” ?And what's the meaning of "puts" and "shutdown"?

### ISSUE THREAD

**Issue by clx7913** [riscv/riscv-asm-manual#9]
In the manual,I found:

```
ld      a1, 0(a0)
...
sd      a1, 0(a0)
```
I know that `ld`  will load the information from memory to register. And the `sd` is the opposite.

But what's the meaning of `0(a0)`? I can't understand this syntax.

Another question:

```
pass:
        la a0, pass_msg
        jal puts
        j shutdown

fail:
        la a0, fail_msg
        jal puts
        j shutdown
```

What's the meaning of "puts" and "shutdown"?

**Comment by jim-wilson** [comment]
puts and shutdown are functions.  puts is a standard C library routine, and writes a string to stdout.  shutdown is a UNIX system command to turn off a computer, the function is emulating this command.

Given "ld a1, 0(a0)", a0 contains an address, 0 is an offset to add to the address, and a1 is the destination register where the load result is to be stored.  This is a standard assembly language format for UNIX assemblers.  "st a1, 0(a0)" is similar, except that a1 is the source register that will be written to the address in a1 plus the offset 0.

**Comment by clx7913** [comment]
Can I simplely reguard `puts` and `shutdown` as placeholders?

**Comment by jim-wilson** [comment]
Yes, jal (jump-and-link) can be used to call any function.  j (jump) can only be used for functions that don't return like shutdown, exit, and abort.

**Comment by jim-wilson** [comment]
We don't have anything like that currently.

We do have a naked attribute that will give you a function with no prologue and epilogue.  It would be possible to write an interrupt handler using a naked function, but you need to register the function as an interrupt handler some other way, and you would need to manually handle any tasks normally handled in the prologue and epilogue if necessary.  It might be easier to do this in assembler.

**Comment by clx7913** [comment]
Got it!

I want to try  the example asm program https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md#control-and-status-registers 
So here is my program:
```
#include "riscv_test.h"
#include "test_macros.h"

RVTEST_RV64U
RVTEST_CODE_BEGIN 

.equ RTC_BASE,      0x40000000
.equ TIMER_BASE,    0x40004000

1:      auipc   t0, %pcrel_hi(mtvec)        
        addi    t0, t0, %pcrel_lo(1b)       
        csrrw   zero, mtvec, t0

        li      t0, 8
        csrrs   zero, mstatus, t0

        li      t0, 128
        csrrs   zero, mie, t0

        li      a0, RTC_BASE
        ld      a1, 0(a0)

        li      a0, TIMER_BASE
        li      t0, 1000000000
        add     a1, a1, t0
        sd      a1, 0(a0)

loop:
        wfi
        j loop

mtvec:
        csrrc  t0, mcause, zero
        bgez t0, fail       
        slli t0, t0, 1      
        srli t0, t0, 1
        li t1, 7            
        bne t0, t1, fail
        j pass

pass:   .string "PASS\n"
        j pass_msg

fail:   .string "FAIL\n"
        j fail_msg

.section .rodata

pass_msg:
        .string "PASS\n"

fail_msg:
        .string "FAIL\n"
RVTEST_CODE_END
```
I just slightly modified it to:  j pass_msg   j fail_msg.
And my building command:
```
root@c:/home/chang/fpga-zynq/rocket-chip/riscv-tools/riscv-tests/isa# riscv64-unknown-elf-gcc -march=rv64g -mabi=lp64 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/home/chang/fpga-zynq/rocket-chip/riscv-tools/riscv-tests/isa/../env/p -I/home/chang/fpga-zynq/rocket-chip/riscv-tools/riscv-tests/isa/macros/scalar -T/home/chang/fpga-zynq/rocket-chip/riscv-tools/riscv-tests/isa/../env/p/link.ld rv64mi/c.S -o rv64ui-p-c
/tmp/ccG2dsjM.o: In function `trap_vector':
(.text.init+0x40): undefined reference to `tohost'
collect2: error: ld returned 1 exit status
```
Is there syntax problem?

**Comment by clx7913** [comment]
I put my own asm file(called c.S) into the riscv-tests/isa/rv64mi/ because I still don't know how to build a single asm file under another directory with specific settings : rv64ui or rv64mi,p or v .etc.  Then putting it into riscv-tests/isa/rv64mi/ is an easy way now.

Yes,you're right.I had not add RVTEST_DATA_BEGIN/RVTEST_DATA_END macros.That's mentioned in the readme file of riscv-tests.

Thanks a lot!

**Comment by clx7913** [comment]
If I add ` jal puts` into my asm program,when building it tells me:
`
rv64ui/simple.S: Assembler messages:
rv64ui/simple.S:10: Error: illegal operands `jalr ra,puts'
`
Need I add`#stdio.h` in the asm?

**Comment by jim-wilson** [comment]
On Wed, May 2, 2018 at 1:42 AM, clx7913 <notifications@github.com> wrote:

> If I add jal puts into my asm program,when building it tells me:
> rv64ui/simple.S: Assembler messages: rv64ui/simple.S:10: Error: illegal
> operandsjalr ra,puts'
> Need I add#stdio.h` in the asm?
>
jalr accepts the destination address as register+offset.  "puts" is not
register+offset.  If you want to call a symbol, you need to use jal instead
of jalr.  jal accepts a pc-relative offset to an address, which can be a
symbol.   Jal only works if the address is in range though.  You can also
use call which emits a two instruction sequence auipc/jalr which loads an
address into a register (t1) and calls it.

An easy way to learn more about RISC-V assembler is to write small
testcases is C, compile with -S to see the assembly language, and also
compile with -c to generate object files and run objdump -dr on them to see
the final code after macros are expanded.

Jim

**Comment by clx7913** [comment]
Thank you sir,it's detailed and very useful to me!
